heat_template_version: 2016-04-08

resources:
  server2:
    type: OS::Nova::Server
    properties:
      image: cirros
      flavor: m1.tiny
      key_name: stack2
      networks:
      - network: admin_internal_net

  server3:
    type: /root/4stackyaml/stack2.yaml
